---
name: "Lint"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-jsonlint:
    uses: timmo001/workflows/.github/workflows/lint-jsonlint.yml@master
  lint-markdown-links:
    uses: timmo001/workflows/.github/workflows/lint-markdown-links.yml@master
  lint-markdownlint:
    uses: timmo001/workflows/.github/workflows/lint-markdownlint.yml@master
  lint-pylint:
    name: Lint (pylint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Create venv (uv)
        run: |
          uv venv
      - name: Install dependencies (uv)
        run: |
          uv pip install -e .
          uv pip install -r requirements.txt -r requirements_test.txt "pylint>=3.2"
      - name: Run pylint (uses pyproject.toml) via uv
        run: |
          uv run pylint --rcfile=pyproject.toml aiolyric
  lint-ruff:
    uses: timmo001/workflows/.github/workflows/lint-ruff.yml@master
