---
name: "Test"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Create venv (uv)
        run: |
          uv venv
      - name: Install deps (uv)
        run: |
          uv pip install -e .
          uv pip install -r requirements.txt -r requirements_test.txt
      - name: Run tests (uv)
        run: |
          uv run pytest -q --disable-warnings --maxfail=1
